name: "Pipeline 2 - Servicios Infraestructura"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "k8s/gke/infra/**"
  workflow_run:
    workflows: ["Pipeline 1 - Infraestructura OKE"]
    types: [completed]

permissions:
  contents: read

jobs:
  gitleaks:
    uses: ./.github/workflows/gitleaks.yml

  deploy-infra:
    name: Deploy Redis + RabbitMQ
    needs: gitleaks
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup OCI CLI
        uses: oracle-actions/configure-oci-cli@v1.3.2
        with:
          user: ${{ secrets.OCI_USER_OCID }}
          tenancy: ${{ secrets.OCI_TENANCY_OCID }}
          fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          privateKey: ${{ secrets.OCI_PRIVATE_KEY }}
          region: ${{ secrets.OCI_REGION }}

      - name: Bajar kubeconfig del OKE
        run: |
          mkdir -p ~/.kube
          oci ce cluster create-kubeconfig \
            --cluster-id ${{ secrets.OKE_CLUSTER_ID }} \
            --file ~/.kube/config \
            --region ${{ secrets.OCI_REGION }} \
            --token-version 2.0.0 \
            --kube-endpoint PUBLIC_ENDPOINT

      - name: Deploy namespace
        run: kubectl apply -f k8s/gke/namespaces.yaml

      - name: Sync RabbitMQ TLS secret from GitHub Secrets
        run: |
          echo "${{ secrets.RABBITMQ_TLS_CERT_B64 }}" | base64 -d > /tmp/rabbitmq-cert.pem
          echo "${{ secrets.RABBITMQ_TLS_KEY_B64 }}"  | base64 -d > /tmp/rabbitmq-key.pem
          kubectl create secret generic rabbitmq-tls -n sdypp \
            --from-file=rabbitmq-cert.pem=/tmp/rabbitmq-cert.pem \
            --from-file=rabbitmq-key.pem=/tmp/rabbitmq-key.pem \
            --dry-run=client -o yaml | kubectl apply -f -
          rm -f /tmp/rabbitmq-cert.pem /tmp/rabbitmq-key.pem

      - name: Deploy infrastructure services
        run: kubectl apply -f k8s/gke/infra/
